name: Rust Audit

on:
  push:
    paths:
      - .github/workflows/audit.yaml
      - "**/audit.toml"
      - "**/Cargo.toml"
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC

permissions:
  checks: write # audit result
  contents: read # git clone

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run cargo audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ github.token }}
